# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f38e490d39e06b5abf2ad9ae16c26aa328e9d134f9d25a552a64cd78d9569f812f12720147912b331229508a5206a82298927ac6a8a618c8c8a1457f0969dab

test:
  secret_key_base: 57ac11eb7f493ec44a3c62b14b23fb7a5c57b48a56c55ec65ef70f702f6d457a593b48cd82677cb47be771e5850dd5a4636d89d3551d1a1a8127347c6e18f658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
